version: '3'
services:
  web:
    container_name: web
    build: .

    volumes:
    - ./:/var/www/app/
    ports:
    - 8080:80
    depends_on:
    - db
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: abc123